name: Deploy

on:
  push:
    branches:
    - "class-3"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        node: [ 18, 20 ]

    steps:
    - name: Print variable
      run: echo "${{ secrets.TOKEN_SECRET }}"

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Build page
      run: npm run build

    - name: Upload artifact
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 18 }}
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: public/

  deploy:
    runs-on: ${{ matrix.os }}
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: deploy
      id: deployment
      uses: actions/deploy-pages@v4
